# Generated by Django 4.2.25 on 2025-10-25 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_sitesetting_remove_post_updated_at_post_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='名前')),
                ('bio', models.TextField(blank=True, verbose_name='プロフィール文')),
                ('icon', models.ImageField(blank=True, null=True, upload_to='profile_icons/', verbose_name='プロフィール画像')),
            ],
        ),
    ]
